### ISSUE TITLE
FEZ (possibly other games) accessing inaccessible paths

### ISSUE THREAD

**Issue by 0x0ade** [AngelDE98/FNADroid#1]
Some games try to access paths that normally are not accessible. Such a path is f.e. /data/.config with FEZ, as /data is Android's HOME environment variable. Only problem with it is that the /data partition is well secured and thus /data/.config is inaccessible.

To be fixed via a patch in Mono or by manually setting the HOME environment variable.

**Comment by flibitijibibo** [comment]
You'll probably care about this block here:

https://github.com/flibitijibibo/FNA/blob/master/src/Storage/StorageDevice.cs#L377

In general, `git grep OSVersion` should point you towards all the places you need to check out when adding new platforms.

It'd be nice to know where to save things, though. Usually it's us attempting to go for XDG_DATA_HOME or XDG_CONFIG_HOME; if there's a specific place we should write to I can add that to the documentation.

**Comment by 0x0ade** [comment]
FNADroid now finally sets the HOME environment variable properly to something accessible on the SD card, related to the app.

Also, with progress in my FNA fork and #2, the game should no longer look outside its given paths.

I'll close this issue as all currently tested games work without root (yet?). FEZ 1.11 is not tested, but with 1.12 on its way and FEZMod taking care of the platform-dependant crash / missing path, this should not be much of an issue for FNADroid itself I guess.
