### ISSUE TITLE
Automatically use device vibration and offer other controller helpers

### ISSUE THREAD

**Issue by 0x0ade** [AngelDE98/FNADroid#4]
Every Android phone (unfortunately not many tablets) and some controllers (not my OUYA controller) offer vibration. I haven't tested the controller vibration yet, but as SDL2 automatically picks up the accelerometer as controller (FEZ is technically "playable" without controller out of the box to some degree), it should also be possible to hook the controller vibration to make the phone vibrate, either via FNA or SDL2 itself.

**Comment by flibitijibibo** [comment]
The controller support in 1.12 will change somewhat; we're removing the custom joystick support in favor of the 360-like support, but in exchange the latter mode will be more customizable, and will continue to use SDL_GameController like it does on Linux/Mac right now.

For the controller support, you'll be interested in the current databases...

https://hg.libsdl.org/SDL/file/c9cae280468f/src/joystick/SDL_gamecontrollerdb.h
https://github.com/gabomdq/SDL_GameControllerDB/

... as well as the environment variable to set controller bindings:

https://hg.libsdl.org/SDL/file/c9cae280468f/include/SDL_hints.h#l312

If someone were to prepare Android entries and submit them to Gabriel's database they could be loaded via that text file and be supported that way. FNA loads gamecontrollerdb.txt when it's available, so as long as the database has it, we'll recognize it. It'll also prevent unrecognized hardware from doing crazy stuff to the game, which happened quite a bit with the old SDL_Joystick path...

**Comment by 0x0ade** [comment]
My horrible FNA fork now contains some controller support (https://github.com/AngelDE98/FNA/commit/a5d225e5a2e0de0712e3864cab88a7fe09a1973d) and FNADroid-CS itself now supports device vibration separately from controller vibration.

I don't know how useful it would be to call FNADroid-CS from FNA itself as this is just an unofficial FNA Android wrapper, but I've thought about hooking the controller vibration to the device vibration.

Do the XNA specs say anything about device vibration? (IIRC Windows Phone was a target)

About the controller support: Blame SDL2 or Android for the lack of proper GUIDs and the lack of events.

**Comment by flibitijibibo** [comment]
If cdevice events aren't being fired I would file that as an SDL2 issue:

https://bugzilla.libsdl.org/

For the vibration, there's a chance that the haptic shows up as a standalone device separate from joystick:

https://wiki.libsdl.org/CategoryForceFeedback
https://wiki.libsdl.org/SDL_HapticName

So if you wanted to, you could try to line up the phone's haptic with the sensor's joystick and have the API remain as-is without modifications. If the haptic doesn't show up even as a standalone device, I'd mark that as an SDL2 issue as well.

**Comment by 0x0ade** [comment]
Controller:

After taking a look into joystick/android/SDL_sysjoystick.c, "the GUID is just the first 16 chars of the name for now" seems to explain the GUID issue. Weirdly (or not?), the JOYDEVICEADDED event is being fired. I've seen a differentiation between GameControllers and Joysticks, but I don't know what's going on.

Vibration:

SDL2 doesn't find any non-controller haptic device and I can't find any calls to the Vibrator class in SDLActivity. Using it would require the VIBRATION permission for the app, so I can understand why it's not of high priority.

I don't feel the need to create issues for these, but am going to create them soon-ish if required.

**Comment by flibitijibibo** [comment]
If it can be done in code, the code needs to be there, even if it won't necessarily be used by apps who want to keep their permissions list small. That can be trimmed down easier than it can be hacked in by who-knows-how-many branches.

**Comment by 0x0ade** [comment]
Submitted a bug report / enhancement: https://bugzilla.libsdl.org/show_bug.cgi?id=3183

Hopefully I didn't screw anything up in the process...

**Comment by 0x0ade** [comment]
Reviving this dead issue even before SDL2 supports vibration. Selfnote-ish comment for what to do when I'm done collecting data with the Windows Phone emulator.

**Accelerometer:**
_MSDN XNA Documentation: https://msdn.microsoft.com/en-us/library/ff604984(v=xnagamestudio.42).aspx (xnagamestudio.42 referring to "Windows Phone SDK 8.0 Extensions for XNA Game Studio 4.0")_
The previous plans were to map the accelerometer as a controller, but XNA / the documentation instead advises the use of Silverlight's Microsoft.Devices.Sensors.Accelerometer. The accelerometer controller may interfere with any controller that may actually be connected as player 1 controller.
FNADroid will thus offer an event to listen to, similar to Accelerometer.ReadingChanged, and methods to poll the data.

**Vibration:**
_MSDN WP Documentation: https://msdn.microsoft.com/library/windows/apps/jj206994(v=vs.105).aspx_
Vibration isn't even specified in the XNA docs. Instead, apps using the vibration functions should instead use Microsoft.Devices.VibrateController. FNADroid's vibration methods already mimic this behavior.
Mapping the device vibration to the controller vibration sounds like a good idea at first (giving games an easy way to vibrate the phone), but actually suffers from the same issue as the accelerometer controller: Interference with actually connected controllers.
It would still be nice to use SDL2's haptic subsystem.

**Comment by 0x0ade** [comment]
https://github.com/0x0ade/FNADroid/commit/bcd34615006c01b4e9d5a20b8926fcfb316169d6 should finally "fix" this issue.

FNADroid offers the static Accelerometer, Gyroscope and Vibration classes in the FNADroid namespace, and the third-party FNA extensions FNADroid.FNADroidPlatform.PhoneAsGamePad and the FNA_GAMEPAD_VIBRATION_PHONE environment variable.

FNADroidPlatform.PhoneAsGamePad is a runtime-settable field. FNADroid implements its own fake gamepad as SDL2 doesn't check SDL_HINT_ACCELEROMETER_AS_JOYSTICK after SDL_SYS_JoystickInit. Currently it's automatically mapped to player 1, pushing the others (sorry, player 4!). The vibration is sent to the phone, the back button behaves as it should in #7 and the left stick is set to the X and Y axes of the accelerometer.

Games wanting to change that behavior but still wanting a phone gamepad should hook FNADroidPlatform.GetPhoneGamePadCapabilitiesHook and FNADroidPlatform.GetPhoneGamePadStateHook.

The FNA_GAMEPAD_VIBRATION_PHONE environment variable makes all GamePad.SetVibration(PlayerIndex.One, l, r) calls vibrate the player 1 gamepad _and_ the phone. To only make the phone vibrate, use either the Vibration class or FNADroidPlatform.PhoneAsGamePad.
